name: simon_game
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # Assets -> assets folder (instead of images)
  assets:
    - assets/

  fonts:
  - family: PressStart2P
    fonts:
    - asset: fonts/PressStart2P-Regular.ttf